### PR TITLE
WIP login page

### PR DESCRIPTION
**Pull request by edenmaor**
created a views.py, added a template for the login page.
 defined a path inside the urls.py for the login page
wrote a login.html page for the login process

### CODE REVIEW

**Review by shayakrach — COMMENTED** [review]
You should work on another branch locally (called it x) and push it remotely with the command "push -u origin x" and not to your origin master.

**Review by AshkenYariv — CHANGES_REQUESTED** [review]
We are still working on the login page, not yet for approval

**Comment by edenmaor** [comment]
@shayakrach why does it matter? I'm working with a different branch on my forked repository.

**Comment by shayakrach** [comment]
I can help with technical issues.

**Comment by AshkenYariv** [comment]
@edenmaor what is the current situation with this, what needs to be fixed? I can help you out today if you need.

**Pull request closed without merging**
