### PR TITLE
Automating our pipenv

### PR DESCRIPTION
**Pull request by AshkenYariv**
Created a "setup.sh" file to run a shell script when VM starts up
for the first time.
Updated Vagrantfile so Vagrant runs "setup.sh" when starting up for the
first time.

### CODE REVIEW

**Review by EdDev — CHANGES_REQUESTED** [review]
You have some typos in the commit message.

**Comment by EdDev** [comment]
There is also something broken with the CI, not necessarily because of this PR.

Please check what is going on.

**Review by assafg95 — APPROVED** [review]

**Review by shayakrach — APPROVED** [review]

**Comment by AshkenYariv** [comment]
Typos have been fixed, the CI is not relevant for this commit.

**Comment by EdDev** [comment]
> You have some typos in the commit message.

The typos have been fixed on the PR description and not in the commit message itself. Please amend the fixes on the commit and push again.

> Varantfile
> whenstarting

**Review by shayakrach — APPROVED** [review]

**Comment by AshkenYariv** [comment]
Hey Ed, the typo has now been fixed in the commit message.

**Review by EdDev — APPROVED** [review]

**Pull request merged**
