### PR TITLE
Fixing of "setup.sh" file

### PR DESCRIPTION
**Pull request by AshkenYariv**
This commit added an additional line to the "setup.sh" file that was
missing.

### CODE REVIEW

**Review by shayakrach — APPROVED** [review]

**Review by assafg95 — APPROVED** [review]

**Review by ormergi — COMMENTED** [review]
Please explain **why** this change is necessary in the commit message and PR description.

**Review by edenmaor — APPROVED** [review]

**Comment by ormergi** [comment]
@AshkenYariv When you close a PR you should write why and follow up PR link if there is one.
Reviewers invest time reviewing your PR and you will probably need them to review the follow up PR as well.

**Comment by yuvalk** [comment]
+1 to what @ormergi said,
also, it is usually better to update the existing PR than opening a new one (assuming the $SUBJECT is still the case of the PR.
if not, then as @ormergi said, better to include a reason why it's no longer relevant

**Comment by AshkenYariv** [comment]
Hi @yuvalk and @ormergi, sorry made this mistake when trying to change the commit message, after it happen @shayakrach explained how to change the commit message next time.
Could you review the new PR I created please?

**Comment by AshkenYariv** [comment]
This PR was closed accidently when trying to change a commit description.
The new PR solving this issue is in the link below:
https://github.com/redhat-beyond/Side-Hustle/pull/14

**Pull request closed without merging**
