### PR TITLE
Fixing active button when adding job

### PR DESCRIPTION
**Pull request by AshkenYariv**
Activation checkbox didn't work when adding a job.

close #68

### CODE REVIEW

**Review by assafg95 — APPROVED** [review]

**Comment by ormergi** [comment]
Is this still a WIP?
If not, make sure you update the PR description and commit messages (they should also include brief description about the problem)

**Review by edenmaor — APPROVED** [review]

**Comment by AshkenYariv** [comment]
> Is this still a WIP? If not, make sure you update the PR description and commit messages (they should also include brief description about the problem)

Fixed.

**Comment by ormergi** [comment]
@AshkenYariv There is no need to repeat the commit message inside its body, please remove it.

Also commit messages should include explain what is the problem / why you need the change and how its going to affect the app (how things used to work and how they are going to work from now on).
And be written in "instructive" way instead of in past tense.

Please change the commit message accordingly.

**Comment by AshkenYariv** [comment]
> @AshkenYariv There is no need to repeat the commit message inside its body, please remove it.
> 
> Also commit messages should include explain what is the problem / why you need the change and how its going to affect the app (how things used to work and how they are going to work from now on). And be written in "instructive" way instead of in past tense.
> 
> Please change the commit message accordingly.

Fixed.

**Comment by ormergi** [comment]
Thanks!

**Pull request merged**
