### PR TITLE
Vagrantfile

### PR DESCRIPTION
**Pull request by assafg95**

### CODE REVIEW

**Comment by yuvalk** [comment]
please remove the `testing pr` commit from this PR.

**Comment by yuvalk** [comment]
also `test file deleted` commit
and I think it's better to split the .gitignore commit from the vagrantfile commit
as they are 2 different, atomic, things

**Comment by yuvalk** [comment]
I can help with the removal of the commits if needed (tip: learn how to use `git rebase -i`)

**Comment by assafg95** [comment]
> also `test file deleted` commit and I think it's better to split the .gitignore commit from the vagrantfile commit as they are 2 different, atomic, things

i don't know how to after i already comitted. can you please help with this?

**Comment by assafg95** [comment]
> please remove the `testing pr` commit from this PR.

I do not see an option to delete this commit here. Do I need to do it on my local repo and then commit again?

**Comment by yuvalk** [comment]
yes, you need to fix it in your local branch first

**Comment by yuvalk** [comment]
looks good now

**Pull request merged**
