### PR TITLE
Delete studentProfile app

### LINKED ISSUE #74: Delete StudentProfile app

### LINKED ISSUE #76: Remigrate files after studentProfile Deletion
Remigrate files after studentProfile

### PR DESCRIPTION
**Pull request by AshkenYariv**
This app was deleted since we decided not to implement it for
the final project since it had no relevant contribution to the
website. Since we did not connect this app with any other apps
this deletion has not effect on the flow of the website.

Close #74 
Close #76

### CODE REVIEW

**Review by ormergi — CHANGES_REQUESTED** [review]
Commit "Delete studentProfile app": please explain in the commit message why.

**Review by ormergi — CHANGES_REQUESTED** [review]
PR title: remove "and remigrating files" part, there is no need to give implementation details on the title.

PR description: please explain why you need to remove it, if it changes the flow of the app make sure you explain how.

Commit "Remigrating studentProfile app": 
There is no need to repeat the title inside the commit message body

Consider merging this commit to the one before, it will make it more atomic meaning that the commit message include all related changes it introducing.
Keeping commits atomic, make the history easier to understand and reduce maintenance effort in case a revert is needed.

**Review by edenmaor — APPROVED** [review]

**Comment by AshkenYariv** [comment]
> Commit "Delete studentProfile app": please explain in the commit message why.

Fixed.

**Comment by AshkenYariv** [comment]
> PR title: remove "and remigrating files" part, there is no need to give implementation details on the title.
> 
> PR description: please explain why you need to remove it, if it changes the flow of the app make sure you explain how.
> 
> Commit "Remigrating studentProfile app": There is no need to repeat the title inside the commit message body
> 
> Consider merging this commit to the one before, it will make it more atomic meaning that the commit message include all related changes it introducing. Keeping commits atomic, make the history easier to understand and reduce maintenance effort in case a revert is needed.

Fixed. I merged this to a single commit.

**Comment by ormergi** [comment]
#68 is merged, you need to rebase.

Also, explain why you decided you delete this app (I dont understand what you meant by "it doesent functional to the website")
if there is no affect on the flow of the app - mention it.

**Comment by AshkenYariv** [comment]
> #68 is merged, you need to rebase.
> 
> Also, explain why you decided you delete this app (I dont understand what you meant by "it doesent functional to the website") if there is no affect on the flow of the app - mention it.

Fixed.

**Review by shayakrach — COMMENTED** [review]
LGTM

**Review by ormergi — APPROVED** [review]
Now it's much more clear, thanks!

**Comment by ormergi** [comment]
Now it much more clearm

**Pull request merged**
