### PR TITLE
Create conftest file

### LINKED ISSUE #43: Move fixtures to conftest.py file
Create a single file with all fixtures.

### PR DESCRIPTION
**Pull request by shayakrach**
Creating a single file with all fixtures.
Moving all the fixtures to this file.
Adding default variables for the fixtures.
That will make the code readable and maintainable, mainly for future work.

close #43, #53

### CODE REVIEW

**Review by assafg95 — APPROVED** [review]

**Review by AshkenYariv — APPROVED** [review]
@shayakrach looks great!

**Review by ormergi — COMMENTED** [review]
Hi Eden, are there any logic (tests code changes) or any kind of refactoring (any of var/method/class change) changes included?

**Comment by shayakrach** [comment]
> Hi Eden, are there any logic (tests code changes) or any kind of refactoring (any of var/method/class change) changes included?

Hi @ormergi, I made this PR.
My changes did not change the logic, but I added some default variables and moved all the fixtures to one file (as I wrote).

**Comment by ormergi** [comment]
> Hi @ormergi, I made this PR. And yes, of course! I added some default variables for the fixtures and moved all the fixtures to one file.

I am so sorry, I confused between you two :man_facepalming: 

Would you please separate to another commit these changes, so there will be one commit for moving and another for refactoring?
It will make it much easier to follow how the code is changed, at the current state this kind of changes are 
pretty much "hidden".

**Comment by shayakrach** [comment]
> state

You are right.
I will change it.

**Comment by shayakrach** [comment]
> > Hi @ormergi, I made this PR. And yes, of course! I added some default variables for the fixtures and moved all the fixtures to one file.
> 
> I am so sorry, I confused between you two 🤦‍♂️
> 
> Would you please separate to another commit these changes, so there will be one commit for moving and another for refactoring? It will make it much easier to follow how the code is changed, at the current state this kind of changes are pretty much "hidden".

You are right.
I will change it.

**Comment by shayakrach** [comment]
@ormergi I separate those changes to another commit.
I hope that is better.

**Review by assafg95 — APPROVED** [review]

**Review by ormergi — APPROVED** [review]
Thank you, now its much easier to follow

**Pull request merged**
