### PR TITLE
Django app with static web page

### PR DESCRIPTION
**Pull request by edenmaor**
- created a basic django project - job board static page

- added migrations and test data

### CODE REVIEW

**Review by shayakrach — APPROVED** [review]

**Review by assafg95 — APPROVED** [review]

**Review by AshkenYariv — APPROVED** [review]

**Comment by yuvalk** [comment]
why there's a merge commit in this PR ?
https://github.com/redhat-beyond/Side-Hustle/pull/10/commits/a6aaa993b77ddc2dbb3d1b502d65ade11be17211

**Comment by edenmaor** [comment]
Because i created the webApp via a new branch locally

בתאריך שבת, 6 בנוב׳ 2021 ב-20:21 מאת Yuval Kashtan ***@***.***

**Comment by yuvalk** [comment]
> Because i created the webApp via a new branch locally

yeah, but we dont need that in the upstream history. can you rebase so we only have meaningful commits?

**Comment by yuvalk** [comment]
also, see that the workflow still fails ..
https://github.com/redhat-beyond/Side-Hustle/runs/4127029290?check_suite_focus=true

**Comment by edenmaor** [comment]
Ok

בתאריך שבת, 6 בנוב׳ 2021 ב-20:25 מאת Yuval Kashtan ***@***.***

**Pull request closed without merging**
