### PR TITLE
Add search methods and tests for Job class model WIP

### PR DESCRIPTION
**Pull request by assafg95**
Fix in conftest.py job fixtures so job1 and job2 are different job_types
and apply_link(needs to be unique)
Add search method and test to return all jobs
Add search method and test to return all jobs by JobType
Add return job_type method

### CODE REVIEW

**Comment by assafg95** [comment]
This PR will add the search methods so we can return sets of jobs from the database. For now I only implemented methods to return all jobs and jobs with the given JobType. Please Let me know if these methods and tests are good so I can continue to add to this PR methods to search by location, title, and then methods that join a few search options together.

**Comment by shayakrach** [comment]
> This PR will add the search methods so we can return sets of jobs from the database. For now I only implemented methods to return all jobs and jobs with the given JobType. Please Let me know if these methods and tests are good so I can continue to add to this PR methods to search by location, title, and then methods that join a few search options together.

Looks fine to me by now.
Add a test that checks that the URLs must be unique.
Also, change the title to WIP and continue.

**Comment by assafg95** [comment]
> > This PR will add the search methods so we can return sets of jobs from the database. For now I only implemented methods to return all jobs and jobs with the given JobType. Please Let me know if these methods and tests are good so I can continue to add to this PR methods to search by location, title, and then methods that join a few search options together.
> 
> Looks fine to me by now. Add a test that checks that the URLs must be unique. Also, change the title to WIP and continue.

Fixed

**Comment by assafg95** [comment]
@yuvalk is there anything else that I need to add besides these basic search methods?

**Comment by assafg95** [comment]
Closing this PR. Search functions are not relevant for the next Demo. Will create a new PR in the future with better functions

**Pull request closed without merging**
