### PR TITLE
Creating Control Logic and UI

### PR DESCRIPTION
**Pull request by AshkenYariv**
3 commits including:
- Deleting non relevant HTML templates
- Updating all models to support Control Logic
- Creation of Control Logic and UI

### CODE REVIEW

**Review by assafg95 — APPROVED** [review]

**Review by shayakrach — APPROVED** [review]
LGTM!

**Comment by yuvalk** [comment]
tests?

**Comment by AshkenYariv** [comment]
> tests?

Tests will be added today and tomorrow by Assaf and Shay

**Review by edenmaor — APPROVED** [review]
Beside the tests that will be completed tonight, looks really good, good job Yariv!

**Comment by yuvalk** [comment]
I know you put effort into this 
so
approving even though, it was really preferable to have tests within the same PR

**Pull request merged**
